services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: bot
      # 개발 환경 설정을 편하게 하기 위한 키값.
      # 운영 환경에서는 개발환경과 같은 키값을 쓰지 않음.
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bot
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: