openai:
  api-key: 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

meta:
  app-id: 123456789012345
  app-secret: abcde12345fghij67890klmnop

#threads:
#  accounts:
#    - user-id: your_threads_user_id_here
#      access-token: your_threads_access_token_here

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/bot
    username: bot
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
